---
- name: Subscribe host and install required packages
  hosts: all
  vars_files: vault.yml
  vars:
    repos:
      - rhel-9-for-x86_64-baseos-rpms
      - rhel-9-for-x86_64-appstream-rpms
      - satellite-6.17-for-rhel-9-x86_64-rpms
      - satellite-maintenance-6.17-for-rhel-9-x86_64-rpms
    packages:
      - fapolicyd
      - satellite
      - rhel-system-roles
      - nfs-utils
      - vim-enhanced
      - virt-who
    ansible_remote_tmp: /dev/shm/ansible
    fapolicyd_setup_enable_service: true
    fapolicyd_setup_integrity: sha256
    fapolicyd_setup_trust: rpmdb,file

  tasks:

    - name: Register to Red Hat Subscription Management Network
      redhat.rhel_system_roles.redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        release: 9.7
        auto_attach: true

    - name: Disable all RHSM repositories
      redhat.rhel_system_roles.rhsm_repository:
        name: '*'
        state: disabled

    - name: Enable required RHSM Repositories
      redhat.rhel_system_roles.rhsm_repository:
        name: "{{ repos }}"
        state: enabled

    - name: Install required packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: latest

    - name: Run the fapolicyd RHEL system role
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.fapolicyd

    - name: Add custom fapolicyd rule for Ansible AAP execution
      ansible.builtin.copy:
        dest: /etc/fapolicyd/rules.d/10-ansible.rules
        content: "allow perm=any uid=admin : dir=/home/admin/.ansible/tmp/\n"
        owner: root
        group: root
        mode: '0644'
      notify: 
        - Compile fapolicyd rules
        - Restart fapolicyd service

    - name: Ensure fapolicyd service is enabled and started
      ansible.builtin.service:
        name: fapolicyd
        state: started
        enabled: true
    
    - name: Add hostname to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^{{ ansible_default_ipv4.address }}.*{{ inventory_hostname }}'
        line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
        state: present
 

  handlers:

    - name: Compile fapolicyd rules
      ansible.builtin.command: fagenrules --load

    - name: Restart fapolicyd service
      ansible.builtin.service:
        name: fapolicyd
        state: restarted
