---
- name: Pull subscription manifest from Red Hat and import to Satellite
  hosts: all 
  vars:
    # Your custom credential definitions (can be passed via Ansible Vault or extra vars)
    satellite_url: "https://dschubba.openincite.net"
    satellite_username: "admin"
    satellite_password: ""
    rhsm_username: "mark_hillis"
    rhsm_password: ""

  roles:
    - role: redhat.satellite.manifest
      vars:
        # Connection variables
        satellite_server_url: "{{ satellite_url }}"
        satellite_username: "{{ satellite_username }}"
        satellite_password: "{{ satellite_password }}"
        satellite_organization: "openincite.net"
        
        # Download and Path variables 
        satellite_manifest_download: true
        satellite_manifest_uuid: "9bfbeddb-2885-4ce0-8bbe-1bc812de39d4"
        satellite_rhsm_username: "{{ rhsm_username }}"
        satellite_rhsm_password: "{{ rhsm_password }}"
        satellite_manifest_path: "~/manifest.zip"
